import type { Crisis, GameState } from "./types.ts";

/** Pressure scales likelihood. Zero means the event cannot fire right now. */
const lack = (value: number, floor: number, k = 0.08) => Math.max(0, (floor - value) * k);

export const CRISES: Crisis[] = [
  {
    id: "hurricane",
    title: "Category 4 Landfall",
    brief:
      "A major hurricane has come ashore over a metro area of four million. Power is out, the airport is under water, and the governor is on television asking where the federal government is.",
    source: "FEMA / Situation Room",
    category: "disaster",
    weight: 1,
    pressure: (s) => 1.2 + lack(s.nation.sectors.environment, 55, 0.05) + lack(s.nation.sectors.infrastructure, 55, 0.05),
    cooldown: 10,
    choices: [
      {
        id: "full-response",
        label: "Full federal deployment",
        detail: "Guard, Army Corps, emergency appropriation. Write the check now, argue later.",
        effects: {
          "politics.approval": 5,
          "nation.unrest": -4,
          "nation.debtToGdp": 0.5,
          "nation.sectors.infrastructure": 2,
          "personal.stress": 8,
        },
        resultText:
          "Convoys are rolling within eighteen hours. The coverage is wall-to-wall and, for once, kind.",
      },
      {
        id: "delegate",
        label: "Let the states lead",
        detail: "Federal support on request only. Cheaper, and it respects the governors.",
        effects: { "politics.capital": 3, "nation.debtToGdp": 0.1 },
        risk: 0.5,
        onFail: { "politics.approval": -8, "nation.unrest": 6, "politics.media": -6, "personal.stress": 10 },
        failText:
          "Two counties go four days without water. The footage runs on a loop with your face beside it.",
        resultText: "The state response holds. You stayed out of the way and it worked.",
      },
      {
        id: "visit",
        label: "Fly there tonight",
        detail: "Boots in the mud, cameras rolling, the whole schedule torn up.",
        effects: {
          "politics.approval": 7,
          "politics.media": 4,
          "personal.stress": 12,
          "personal.health": -2,
          "personal.family": -3,
          "nation.debtToGdp": 0.3,
        },
        resultText:
          "You stand in a flooded gymnasium and listen for two hours. It leads every broadcast.",
      },
    ],
  },
  {
    id: "bank-run",
    title: "A Bank Is Failing",
    brief:
      "The nation's fourth-largest regional lender cannot meet withdrawals. Treasury says contagion is possible by Monday. The markets open in fourteen hours.",
    source: "Treasury Secretary",
    category: "economic",
    weight: 1,
    pressure: (s) => (s.nation.growth < 1 ? 2.2 : 0.5) + Math.max(0, s.nation.inflation - 4) * 0.4,
    cooldown: 14,
    choices: [
      {
        id: "backstop",
        label: "Guarantee all deposits",
        detail: "Unlimited backstop announced before the open. It ends the panic and enrages half the country.",
        capitalCost: 12,
        effects: {
          "nation.growth": 0.3,
          "nation.debtToGdp": 1.2,
          "politics.approval": -4,
          "nation.unrest": 3,
          "personal.stress": 10,
        },
        resultText: "The run stops at 9:31am. By noon the phrase 'bailout' is everywhere.",
      },
      {
        id: "orderly",
        label: "Force an orderly sale",
        detail: "Regulators broker a takeover overnight. Shareholders are wiped out; depositors are made whole.",
        capitalCost: 8,
        effects: { "nation.growth": -0.15, "politics.media": 3, "personal.stress": 8 },
        risk: 0.3,
        onFail: {
          "nation.growth": -0.8,
          "nation.unemployment": 0.5,
          "politics.approval": -7,
          "nation.unrest": 5,
        },
        failText: "No buyer materialises. Two more lenders wobble by Thursday.",
        resultText: "A rival bank swallows it whole by Sunday night. Barely a ripple.",
      },
      {
        id: "let-fail",
        label: "Let it fail",
        detail: "Moral hazard is real. So is a recession.",
        effects: {
          "nation.growth": -0.7,
          "nation.unemployment": 0.4,
          "politics.approval": -3,
          "politics.party": 4,
          "personal.integrity": 3,
        },
        resultText:
          "The bank goes down. You are called principled and reckless in the same paragraph, repeatedly.",
      },
    ],
  },
  {
    id: "standoff",
    title: "Naval Standoff",
    brief:
      "A rival power has surrounded a contested island with 'fishing vessels' that are visibly not fishing vessels. An allied government is asking, publicly, what your treaty commitment is worth.",
    source: "National Security Advisor",
    category: "foreign",
    weight: 1,
    pressure: (s) => 0.8 + lack(s.nation.security, 60, 0.06) + lack(s.nation.standing, 55, 0.04),
    cooldown: 12,
    choices: [
      {
        id: "carrier",
        label: "Send a carrier group",
        detail: "Visible, immediate, and impossible to walk back quietly.",
        capitalCost: 10,
        effects: { "nation.security": 6, "nation.standing": 5, "personal.stress": 12 },
        risk: 0.22,
        onFail: {
          "nation.security": -6,
          "nation.standing": -4,
          "nation.growth": -0.3,
          "politics.approval": -5,
          "personal.stress": 12,
        },
        failText: "A collision at sea kills four sailors. The escalation ladder is suddenly very short.",
        resultText: "They withdraw the vessels within nine days without ever admitting they were there.",
      },
      {
        id: "sanctions",
        label: "Coordinated sanctions",
        detail: "Slow, multilateral, and it hurts your own importers too.",
        capitalCost: 6,
        effects: {
          "nation.standing": 4,
          "nation.inflation": 0.3,
          "nation.growth": -0.15,
          "nation.security": 2,
        },
        resultText: "Eleven allies sign on. The island stays contested; the point is made.",
      },
      {
        id: "backchannel",
        label: "Open a back channel",
        detail: "Quiet talks, no cameras, and no way to claim credit if it works.",
        effects: { "nation.standing": 2, "personal.stress": 5 },
        risk: 0.35,
        onFail: { "nation.standing": -7, "nation.security": -4, "politics.media": -5, "politics.approval": -4 },
        failText: "The channel leaks. You are accused of negotiating with a gun to an ally's head.",
        resultText: "A deal is reached in a hotel in Geneva that no one will ever write about.",
      },
    ],
  },
  {
    id: "cyberattack",
    title: "Grid Intrusion",
    brief:
      "Someone is inside the control systems of three regional utilities. They have not turned anything off yet. That appears to be a choice.",
    source: "Cyber Command",
    category: "domestic",
    weight: 1,
    pressure: (s) => 0.7 + lack(s.nation.sectors.infrastructure, 55, 0.06) + lack(s.nation.sectors.science, 55, 0.04),
    cooldown: 14,
    choices: [
      {
        id: "go-public",
        label: "Go public and harden",
        detail: "Tell the country, mandate emergency standards, absorb the panic.",
        effects: {
          "nation.sectors.infrastructure": 4,
          "nation.security": 3,
          "nation.unrest": 4,
          "politics.approval": -2,
          "politics.media": 4,
        },
        resultText: "Three weeks of frightening headlines buy you a decade of better defaults.",
      },
      {
        id: "quiet-fix",
        label: "Fix it quietly",
        detail: "No announcement. Utilities patch under an emergency order nobody reads.",
        effects: { "nation.security": 2, "politics.capital": 2 },
        risk: 0.4,
        onFail: {
          "politics.media": -8,
          "personal.integrity": -6,
          "politics.scandal": 8,
          "politics.approval": -6,
        },
        failText: "A utility engineer talks to a reporter. The cover-up is now the story.",
        resultText: "The intrusion is scrubbed in eleven days and never makes a front page.",
      },
      {
        id: "retaliate",
        label: "Authorize a response",
        detail: "Offensive cyber against the responsible ministry. Deniable, mostly.",
        capitalCost: 8,
        effects: { "nation.security": 5, "nation.standing": -2, "personal.stress": 8 },
        risk: 0.3,
        onFail: { "nation.security": -5, "nation.standing": -6, "nation.growth": -0.2, "personal.stress": 10 },
        failText: "They escalate. A refinery goes offline for six days and everyone knows why.",
        resultText: "Their ministry loses email for a week. The intrusions stop.",
      },
    ],
  },
  {
    id: "opioid",
    title: "Overdose Surge",
    brief:
      "A new synthetic has pushed overdose deaths up forty percent in a single quarter. County morgues in four states are over capacity.",
    source: "Surgeon General",
    category: "domestic",
    weight: 1,
    pressure: (s) => lack(s.nation.sectors.healthcare, 60, 0.1) + 0.3,
    cooldown: 16,
    choices: [
      {
        id: "public-health",
        label: "Treat it as a health emergency",
        detail: "Naloxone everywhere, treatment beds funded, prosecution deprioritised for users.",
        capitalCost: 6,
        effects: {
          "nation.sectors.healthcare": 6,
          "nation.unrest": -3,
          "politics.approval": 2,
          "nation.debtToGdp": 0.3,
          "politics.party": -2,
        },
        resultText: "Deaths plateau within two quarters. The counties stop calling it a morgue problem.",
      },
      {
        id: "enforcement",
        label: "Enforcement surge",
        detail: "Interdiction, trafficking prosecutions, pressure on the source countries.",
        effects: {
          "nation.sectors.justice": 5,
          "nation.security": 2,
          "nation.standing": -2,
          "nation.sectors.healthcare": -1,
        },
        risk: 0.35,
        onFail: { "politics.approval": -4, "nation.unrest": 4 },
        failText: "Seizures triple. So do deaths. The supply just got more concentrated.",
        resultText: "Two major networks are dismantled and the wholesale price doubles.",
      },
    ],
  },
  {
    id: "strike",
    title: "National Rail Strike",
    brief:
      "Four unions have walked. Freight stops in seventy-two hours, which means grocery shelves in ten days. Both sides expect you to break the other one.",
    source: "Labor Secretary",
    category: "economic",
    weight: 1,
    pressure: (s) => 0.6 + Math.max(0, s.nation.inflation - 3) * 0.4 + lack(s.nation.sectors.welfare, 50, 0.05),
    cooldown: 14,
    choices: [
      {
        id: "side-labor",
        label: "Back the workers",
        detail: "Push the carriers to settle. Your base will love it; the business press will not.",
        capitalCost: 8,
        effects: {
          "politics.party": 6,
          "nation.unrest": -4,
          "nation.inflation": 0.25,
          "nation.growth": -0.1,
          "politics.media": -3,
        },
        resultText: "A deal in nine days with paid sick leave in it. The trains move.",
      },
      {
        id: "impose",
        label: "Impose a settlement",
        detail: "Use federal authority to force them back to work under the last offer.",
        capitalCost: 10,
        effects: {
          "nation.growth": 0.1,
          "nation.unrest": 8,
          "politics.party": -8,
          "politics.approval": -3,
        },
        resultText: "Freight resumes Monday. The unions will remember this in November.",
      },
      {
        id: "mediate",
        label: "Mediate personally",
        detail: "Both sides in the Roosevelt Room until there is white smoke.",
        effects: { "personal.stress": 12, "personal.family": -4, "personal.health": -1 },
        risk: 0.35,
        onFail: {
          "nation.growth": -0.4,
          "nation.unrest": 7,
          "politics.approval": -6,
          "nation.inflation": 0.4,
        },
        failText: "Talks collapse on day six. Shelves empty on day eleven and it is your table they walked away from.",
        resultText: "Eighty hours in a windowless room and they sign. You look terrible and it was worth it.",
      },
    ],
  },
  {
    id: "outbreak",
    title: "Novel Respiratory Outbreak",
    brief:
      "Two hundred cases in three cities of something no one has a test for. The modelling team will not give you a number they are confident in.",
    source: "CDC Director",
    category: "disaster",
    weight: 1,
    pressure: (s) => (s.bills.some((b) => b.id === "pandemic" && b.status === "passed") ? 0.3 : 1.1) + lack(s.nation.sectors.healthcare, 55, 0.05),
    cooldown: 20,
    choices: [
      {
        id: "aggressive",
        label: "Move hard and early",
        detail: "Travel restrictions, emergency production, guidance the country will resent.",
        capitalCost: 10,
        effects: {
          "nation.sectors.healthcare": 4,
          "nation.growth": -0.4,
          "nation.unrest": 5,
          "politics.approval": -3,
          "personal.stress": 14,
        },
        resultText:
          "It burns out in eleven weeks. You will never be able to prove what you prevented.",
      },
      {
        id: "measured",
        label: "Follow the data",
        detail: "Targeted measures only, escalating if the curve turns.",
        effects: { "personal.stress": 8 },
        risk: 0.45,
        onFail: {
          "nation.sectors.healthcare": -8,
          "nation.growth": -1.1,
          "nation.unemployment": 0.9,
          "politics.approval": -10,
          "nation.unrest": 8,
          "personal.stress": 15,
        },
        failText: "The curve turns. You lost three weeks and the country knows exactly how many.",
        resultText: "The cluster stays a cluster. The economy never notices.",
      },
      {
        id: "downplay",
        label: "Keep it calm",
        detail: "No restrictions, reassuring language, protect the recovery.",
        effects: { "nation.growth": 0.15, "politics.media": -4 },
        risk: 0.6,
        onFail: {
          "nation.sectors.healthcare": -10,
          "nation.growth": -1.4,
          "politics.approval": -14,
          "personal.integrity": -8,
          "politics.scandal": 10,
        },
        failText: "It gets away from you completely, and the tape of your reassurance runs forever.",
        resultText: "It fades on its own. You got away with it and you know you got away with it.",
      },
    ],
  },
  {
    id: "court-vacancy",
    title: "A Seat Opens",
    brief:
      "A Supreme Court justice has died. You have a nomination to make and roughly ninety days in which the entire country will talk about nothing else.",
    source: "White House Counsel",
    category: "domestic",
    weight: 0.8,
    pressure: () => 0.5,
    cooldown: 30,
    choices: [
      {
        id: "base-pick",
        label: "Nominate a movement judge",
        detail: "Your side has waited a generation for this seat.",
        capitalCost: 18,
        effects: {
          "politics.party": 12,
          "nation.unrest": 6,
          "politics.approval": -2,
          "politics.media": -4,
          "personal.stress": 10,
        },
        resultText: "Confirmed on a party-line vote after six brutal weeks. Your base is euphoric.",
      },
      {
        id: "consensus",
        label: "Nominate a consensus judge",
        detail: "A respected circuit judge nobody can plausibly call an extremist.",
        capitalCost: 10,
        effects: {
          "politics.media": 6,
          "politics.approval": 3,
          "politics.party": -8,
          "nation.unrest": -2,
        },
        resultText: "Confirmed 78-22. Half your party calls it a wasted seat.",
      },
      {
        id: "deal",
        label: "Trade the seat",
        detail: "Let the other side have the nominee in exchange for the votes you need elsewhere.",
        capitalCost: 4,
        effects: {
          "politics.capital": 18,
          "politics.party": -14,
          "politics.house": 3,
          "politics.senate": 3,
          "personal.integrity": -3,
        },
        resultText: "You get a legislative window nobody expected. Your party will never forgive it.",
      },
    ],
  },
  {
    id: "leak",
    title: "The Leak",
    brief:
      "A reporter has your deputy chief of staff's texts. They are not criminal. They are humiliating, and they contradict something you said from the podium.",
    source: "Press Secretary",
    category: "personal",
    weight: 1,
    pressure: (s) => 0.3 + s.politics.scandal * 0.05 + Math.max(0, 45 - s.politics.media) * 0.03,
    cooldown: 10,
    choices: [
      {
        id: "own-it",
        label: "Get ahead of it",
        detail: "Release everything yourself, take the questions, eat the bad day.",
        effects: {
          "politics.scandal": -8,
          "personal.integrity": 5,
          "politics.approval": -3,
          "politics.media": 5,
          "personal.stress": 8,
        },
        resultText: "One terrible news cycle instead of six. The press corps notices.",
      },
      {
        id: "fire",
        label: "Fire the deputy",
        detail: "Someone has to go, and it is not going to be you.",
        effects: {
          "politics.scandal": -4,
          "politics.approval": -1,
          "politics.party": -3,
          "personal.integrity": -3,
          "personal.stress": 5,
        },
        resultText: "A resignation letter by 6pm. The story lives another two days, then dies.",
      },
      {
        id: "stonewall",
        label: "Deny everything",
        detail: "No comment, no cooperation, no documents.",
        effects: { "politics.media": -6 },
        risk: 0.55,
        onFail: {
          "politics.scandal": 16,
          "personal.integrity": -10,
          "politics.approval": -8,
          "politics.media": -8,
        },
        failText: "The second tranche of texts is worse, and now there is a subpoena with it.",
        resultText: "It never gets past the third day. Nobody can prove a thing.",
      },
    ],
  },
  {
    id: "health-scare",
    title: "Chest Pains",
    brief:
      "You woke at 4am unable to get a full breath. The White House physician wants you at Walter Reed today, and wants it on the record.",
    source: "White House Physician",
    category: "personal",
    weight: 1.2,
    pressure: (s) => lack(s.personal.health, 65, 0.11) + Math.max(0, s.personal.stress - 70) * 0.05,
    cooldown: 8,
    choices: [
      {
        id: "go-now",
        label: "Go today, disclose it",
        detail: "Cancel the schedule. Tell the country. Let them worry for an afternoon.",
        effects: {
          "personal.health": 7,
          "personal.stress": -12,
          "politics.approval": -2,
          "politics.media": 4,
          "personal.integrity": 3,
        },
        resultText:
          "A stent, two nights, and a physician's statement. The markets shrug by Thursday.",
      },
      {
        id: "quiet-visit",
        label: "Go quietly at the weekend",
        detail: "No announcement. A routine physical, officially.",
        effects: { "personal.health": 4, "personal.stress": -5 },
        risk: 0.4,
        onFail: {
          "politics.scandal": 10,
          "personal.integrity": -7,
          "politics.media": -7,
          "politics.approval": -5,
        },
        failText: "A photographer gets the motorcade at the hospital gate. Now it is a cover-up.",
        resultText: "In and out on a Sunday. Nobody files a word about it.",
      },
      {
        id: "ignore",
        label: "Push through it",
        detail: "There is a summit on Tuesday. It was probably the coffee.",
        effects: { "personal.health": -10, "personal.stress": 6, "politics.capital": 3 },
        resultText:
          "You make the summit. You also make the stairs to Marine One look considerably harder than last year.",
      },
    ],
  },
  {
    id: "marriage",
    title: "An Ultimatum",
    brief:
      "Your spouse has asked for a conversation with the door closed and no staff. They have been asking for six weeks. Tonight they stopped asking.",
    source: "The Residence",
    category: "personal",
    weight: 1.2,
    pressure: (s) => lack(s.personal.marriage, 55, 0.11),
    cooldown: 8,
    choices: [
      {
        id: "clear-week",
        label: "Clear the week",
        detail: "Camp David. No staff, no calls, no briefing book. The country can wait five days.",
        effects: {
          "personal.marriage": 20,
          "personal.family": 8,
          "personal.stress": -15,
          "politics.capital": -8,
          "politics.approval": -2,
        },
        resultText: "Five days of walking and talking. You come back with a marriage and a backlog.",
      },
      {
        id: "counseling",
        label: "Agree to counselling",
        detail: "Weekly, in the residence, permanently on the schedule.",
        effects: { "personal.marriage": 11, "personal.stress": -5, "personal.health": 2 },
        resultText: "Thursdays at seven, blocked out for the rest of the term. It helps.",
      },
      {
        id: "later",
        label: "Ask for more time",
        detail: "After the vote. After the summit. After the midterms.",
        effects: { "personal.marriage": -12, "personal.stress": 8, "politics.capital": 4 },
        resultText: "They say they understand. The way they say it is the problem.",
      },
    ],
  },
  {
    id: "child",
    title: "Your Daughter's Number",
    brief:
      "Your youngest was photographed leaving a club at 3am and the picture is being sold. She is nineteen. She has not picked up your calls since Tuesday.",
    source: "The Residence",
    category: "personal",
    weight: 1.1,
    pressure: (s) => lack(s.personal.family, 55, 0.1),
    cooldown: 10,
    choices: [
      {
        id: "protect",
        label: "Protect her publicly",
        detail: "A statement from the podium: my child is not a public figure. Then get on a plane.",
        effects: {
          "personal.family": 16,
          "politics.approval": 2,
          "politics.media": -2,
          "personal.stress": 4,
        },
        resultText: "The photo runs anyway. She calls you back that night, which is the part that matters.",
      },
      {
        id: "ignore-it",
        label: "Say nothing",
        detail: "Engaging feeds it. Let it burn out on its own.",
        effects: { "personal.family": -10, "personal.stress": 6 },
        risk: 0.3,
        onFail: { "politics.scandal": 6, "politics.approval": -3, "personal.family": -6 },
        failText: "It does not burn out. A second photographer follows her to campus.",
        resultText: "Four days and it is gone from the news. She is still not speaking to you.",
      },
      {
        id: "security",
        label: "Assign her a detail",
        detail: "Full protective detail, whether she wants it or not.",
        effects: { "personal.family": -5, "personal.stress": -3, "politics.capital": -2 },
        resultText: "She is safe and furious. You will take safe.",
      },
    ],
  },
  {
    id: "border-surge",
    title: "Border Surge",
    brief:
      "Crossings have tripled in six weeks. Processing centres are at four times capacity and there is footage from inside one of them.",
    source: "Homeland Security",
    category: "domestic",
    weight: 1,
    pressure: (s) => 0.6 + lack(s.nation.security, 60, 0.05) + Math.max(0, s.nation.unrest - 40) * 0.03,
    cooldown: 14,
    choices: [
      {
        id: "capacity",
        label: "Fund capacity and judges",
        detail: "Emergency money for processing, housing, and two hundred new immigration judges.",
        capitalCost: 8,
        effects: {
          "nation.sectors.justice": 4,
          "nation.unrest": -3,
          "nation.debtToGdp": 0.3,
          "politics.approval": 1,
          "politics.media": 3,
        },
        resultText: "The backlog starts falling within a quarter. The footage stops.",
      },
      {
        id: "crackdown",
        label: "Emergency restrictions",
        detail: "Suspend processing at the busiest sectors and deploy the Guard.",
        capitalCost: 10,
        effects: {
          "nation.security": 5,
          "nation.unrest": 6,
          "politics.party": -5,
          "politics.approval": 2,
          "nation.standing": -3,
        },
        resultText: "Crossings fall by half in a month. The courts will be hearing about it for years.",
      },
      {
        id: "regional",
        label: "Regional agreement",
        detail: "Pay three neighbouring governments to process asylum claims at source.",
        capitalCost: 6,
        effects: { "nation.standing": 3, "nation.debtToGdp": 0.2, "nation.security": 2 },
        risk: 0.35,
        onFail: { "nation.standing": -5, "politics.approval": -4, "nation.unrest": 4 },
        failText: "One partner takes the money and does nothing. It is reported in detail.",
        resultText: "Two of the three deliver. Crossings ease without a single soldier deployed.",
      },
    ],
  },
  {
    id: "inflation-spike",
    title: "Prices Break Out",
    brief:
      "Core inflation printed far above forecast for the third month. The central bank is signalling it will do whatever it takes, which means unemployment.",
    source: "Council of Economic Advisers",
    category: "economic",
    weight: 1,
    pressure: (s) => Math.max(0, s.nation.inflation - 3.5) * 1.2,
    cooldown: 10,
    choices: [
      {
        id: "back-fed",
        label: "Publicly back the central bank",
        detail: "Endorse the hikes, absorb the recession, protect the currency.",
        effects: {
          "nation.inflation": -0.8,
          "nation.growth": -0.4,
          "nation.unemployment": 0.4,
          "politics.approval": -4,
          "politics.media": 5,
        },
        resultText: "Inflation expectations come off the boil. So does the labour market.",
      },
      {
        id: "supply",
        label: "Attack it from the supply side",
        detail: "Suspend tariffs, release reserves, unclog ports.",
        capitalCost: 8,
        effects: {
          "nation.inflation": -0.5,
          "nation.growth": 0.1,
          "nation.standing": -2,
          "nation.sectors.infrastructure": 2,
        },
        resultText: "Goods prices ease within two months. Services do not, but it buys time.",
      },
      {
        id: "blame",
        label: "Blame the price gougers",
        detail: "Hearings, jawboning, an antitrust push at the grocery chains.",
        effects: { "politics.approval": 3, "nation.inflation": 0.1, "politics.media": -4, "personal.integrity": -2 },
        resultText: "It polls beautifully and does almost nothing. Both facts are widely reported.",
      },
    ],
  },
  {
    id: "ally-attacked",
    title: "An Ally Is Invaded",
    brief:
      "A treaty ally's border has been crossed by armour at 4am local. They have invoked the mutual defence clause. Your ambassador is asking for an answer within the hour.",
    source: "Situation Room",
    category: "foreign",
    weight: 0.9,
    pressure: (s) => 0.4 + lack(s.nation.standing, 50, 0.05) + lack(s.nation.security, 55, 0.05),
    cooldown: 24,
    choices: [
      {
        id: "commit",
        label: "Commit forces",
        detail: "Honour the treaty in full. This is what the treaty is.",
        capitalCost: 20,
        effects: {
          "nation.standing": 12,
          "nation.security": -4,
          "nation.debtToGdp": 2,
          "nation.growth": -0.4,
          "nation.unrest": 6,
          "personal.stress": 20,
          "personal.health": -3,
        },
        resultText:
          "The line holds. You start writing letters to families and you do not stop for the rest of your term.",
      },
      {
        id: "arm",
        label: "Arms and intelligence only",
        detail: "Everything short of troops. Enormous shipments, no boots.",
        capitalCost: 12,
        effects: {
          "nation.standing": 5,
          "nation.debtToGdp": 1.1,
          "nation.security": 2,
          "personal.stress": 14,
        },
        risk: 0.3,
        onFail: { "nation.standing": -8, "nation.security": -5, "politics.approval": -5 },
        failText: "It is not enough. The capital falls in eleven days and the alliance notices.",
        resultText: "The invasion stalls at the second river. The alliance holds together.",
      },
      {
        id: "diplomacy-only",
        label: "Sanctions and the UN",
        detail: "No weapons, no troops. Isolation and a ceasefire push.",
        effects: {
          "nation.standing": -10,
          "nation.security": -3,
          "nation.growth": -0.1,
          "politics.party": -5,
          "politics.approval": -3,
        },
        resultText:
          "You keep the country out of a war. Three allies open talks with the other side within a year.",
      },
    ],
  },
  {
    id: "wildfire",
    title: "Fire Season",
    brief:
      "Two million acres are burning across four states and the smoke has reached the eastern seaboard. It is the third record year in a row.",
    source: "Interior Department",
    category: "disaster",
    weight: 1,
    pressure: (s) => 0.5 + lack(s.nation.sectors.environment, 60, 0.09),
    cooldown: 12,
    choices: [
      {
        id: "emergency-climate",
        label: "Declare a climate emergency",
        detail: "Unlock emergency authorities and spend against them. It will be litigated for years.",
        capitalCost: 14,
        effects: {
          "nation.sectors.environment": 8,
          "nation.standing": 4,
          "politics.party": 5,
          "nation.unrest": 4,
          "nation.debtToGdp": 0.6,
          "politics.media": 3,
        },
        resultText: "The authorities hold up in the first three courts. The spending starts immediately.",
      },
      {
        id: "suppression",
        label: "Fund suppression and recovery",
        detail: "Aircraft, crews, and rebuilding money. No structural argument.",
        effects: {
          "politics.approval": 3,
          "nation.debtToGdp": 0.4,
          "nation.sectors.environment": 2,
          "personal.stress": 5,
        },
        resultText: "The fires are out by October. The next season is somebody's problem.",
      },
    ],
  },
  {
    id: "cabinet-resignation",
    title: "A Resignation Letter",
    brief:
      "Your Treasury Secretary is resigning over the budget, and intends to say why on the way out. The letter is already with two newspapers.",
    source: "Chief of Staff",
    category: "domestic",
    weight: 0.9,
    pressure: (s) => 0.3 + Math.max(0, 40 - s.politics.party) * 0.05 + Math.max(0, s.nation.debtToGdp - 115) * 0.03,
    cooldown: 16,
    choices: [
      {
        id: "gracious",
        label: "Let them go gracefully",
        detail: "A warm statement, a Rose Garden send-off, no rebuttal.",
        effects: { "politics.media": 4, "politics.approval": -2, "personal.stress": 5, "politics.capital": -4 },
        resultText: "The letter runs and the story is over in three days. Grace is cheap and it works.",
      },
      {
        id: "fight",
        label: "Rebut it hard",
        detail: "Your people brief against them within the hour.",
        effects: {
          "politics.party": 4,
          "politics.media": -6,
          "politics.scandal": 5,
          "politics.approval": -3,
        },
        resultText: "It becomes a two-week fight with a former cabinet member. You do not win it.",
      },
      {
        id: "promote-deputy",
        label: "Promote the deputy immediately",
        detail: "Name a successor within the hour and change the subject with competence.",
        capitalCost: 6,
        effects: { "politics.capital": -2, "nation.growth": 0.1, "politics.media": 2, "politics.approval": 1 },
        resultText: "Markets barely move. The continuity is the message.",
      },
    ],
  },
  {
    id: "shooting",
    title: "Mass Shooting",
    brief:
      "Nineteen dead at a shopping centre, eleven of them under sixteen. You are expected to speak within four hours and there is nothing to say that you have not said before.",
    source: "Chief of Staff",
    category: "domestic",
    weight: 1,
    pressure: (s) => 0.7 + lack(s.nation.sectors.justice, 55, 0.05) + Math.max(0, s.nation.unrest - 45) * 0.03,
    cooldown: 12,
    choices: [
      {
        id: "push-legislation",
        label: "Spend everything on a bill",
        detail: "Go to the Capitol yourself and burn political capital until something passes.",
        capitalCost: 16,
        effects: {
          "nation.sectors.justice": 5,
          "nation.unrest": -4,
          "politics.party": 6,
          "politics.approval": 2,
          "personal.stress": 12,
        },
        risk: 0.4,
        onFail: {
          "politics.approval": -5,
          "politics.capital": -6,
          "nation.unrest": 5,
          "personal.stress": 12,
        },
        failText: "It dies in the Senate in eleven days and you spent everything on it.",
        resultText: "A narrow bill passes. It is less than you wanted and more than anyone expected.",
      },
      {
        id: "executive",
        label: "Executive action",
        detail: "Everything you can do with a pen alone, announced Friday.",
        effects: {
          "nation.sectors.justice": 2,
          "nation.unrest": 2,
          "politics.party": 3,
          "politics.media": 1,
        },
        resultText: "Three rules that will be enjoined by a district judge inside a month. It is something.",
      },
      {
        id: "mourn",
        label: "Go and grieve with them",
        detail: "No policy. Just the families, all afternoon, off camera.",
        effects: {
          "politics.approval": 3,
          "personal.stress": 14,
          "personal.health": -2,
          "nation.unrest": -1,
          "personal.integrity": 3,
        },
        resultText:
          "You sit with nineteen families. You do not sleep that night, or particularly well for a month.",
      },
    ],
  },
  {
    id: "primary-threat",
    title: "A Challenger",
    brief:
      "A governor from your own party is 'praying about' a primary challenge, which is how they announce these things. Your party's donors are taking meetings.",
    source: "Political Director",
    category: "domestic",
    weight: 0.9,
    pressure: (s) => (s.month > 24 ? 0.6 : 0.1) + Math.max(0, 55 - s.politics.party) * 0.06,
    cooldown: 12,
    choices: [
      {
        id: "buy-off",
        label: "Offer them a cabinet seat",
        detail: "A big job with a big title and no independent base.",
        capitalCost: 12,
        effects: { "politics.party": 10, "personal.integrity": -3, "politics.capital": -4 },
        resultText: "They take Commerce. The prayers conclude.",
      },
      {
        id: "crush",
        label: "Crush it early",
        detail: "Lock up the state parties and the donors before they announce.",
        capitalCost: 16,
        effects: { "politics.party": 6, "politics.media": -3, "personal.stress": 8, "politics.approval": -1 },
        risk: 0.25,
        onFail: { "politics.party": -10, "politics.approval": -4, "politics.capital": -8 },
        failText: "They announce anyway, wounded and furious, and now it is a real primary.",
        resultText: "Twenty-six state chairs endorse you in a single week. There is no challenge.",
      },
      {
        id: "ignore-challenger",
        label: "Ignore them",
        detail: "Govern. Let them make their own case.",
        effects: { "politics.capital": 4 },
        risk: 0.4,
        onFail: { "politics.party": -12, "politics.approval": -3 },
        failText: "They announce in Iowa to a full room. Your own party starts hedging.",
        resultText: "The moment passes. They endorse you in the spring through gritted teeth.",
      },
    ],
  },
];

export function eligibleCrises(s: GameState): Crisis[] {
  return CRISES.filter((c) => {
    const last = s.crisisHistory[c.id];
    if (last !== undefined && s.month - last < c.cooldown) return false;
    return c.pressure(s) > 0;
  });
}
