class_name EpilogueScreen
extends CanvasLayer
## End-of-run legacy screen.
##
## Displays the strings generated by EpilogueGenerator using Label nodes and
## offers a single "Play Again" button that resets the run through GameState.

const GENERATOR := preload("res://scripts/core/epilogue_generator.gd")

const HEADING_COLOR := Color(0.94, 0.95, 0.97, 1.0)
const VERDICT_COLOR := Color(0.95, 0.84, 0.42, 1.0)
const BODY_COLOR := Color(0.82, 0.85, 0.91, 1.0)

## Resolved by path rather than the bare autoload name, matching the HUD and
## CabinetDossier. The shipped game supplies /root/GameState via project.godot.
var _state: Node = null
var _verdict_label: Label
var _fates_box: VBoxContainer


func _ready() -> void:
	layer = 30
	_state = get_node_or_null("/root/GameState")
	_build()
	_populate()


func _generate() -> Dictionary:
	var generator := GENERATOR.new()
	if generator != null:
		return generator.generate_legacy()
	return {}


# ------------------------------------------------------------------ the build

func _build() -> void:
	var dim := ColorRect.new()
	dim.name = "Dim"
	dim.color = Color(0.01, 0.015, 0.025, 0.88)
	dim.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	dim.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(dim)

	var centre := CenterContainer.new()
	centre.name = "Centre"
	centre.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(centre)

	var panel := PanelContainer.new()
	panel.name = "Panel"
	panel.custom_minimum_size = Vector2(720.0, 460.0)
	centre.add_child(panel)

	var style := StyleBoxFlat.new()
	style.bg_color = Color(0.02, 0.03, 0.05, 0.96)
	style.border_color = Color(0.85, 0.88, 0.94, 0.18)
	style.set_border_width_all(1)
	style.set_corner_radius_all(14)
	style.content_margin_left = 26.0
	style.content_margin_right = 26.0
	style.content_margin_top = 24.0
	style.content_margin_bottom = 22.0
	panel.add_theme_stylebox_override("panel", style)

	var column := VBoxContainer.new()
	column.name = "Column"
	column.add_theme_constant_override("separation", 12)
	panel.add_child(column)

	var heading := _make_label("The Legacy of Your Presidency", 26, HEADING_COLOR)
	heading.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	column.add_child(heading)

	column.add_child(_make_label("Re-Election Verdict", 18, HEADING_COLOR))
	_verdict_label = _make_label("", 22, VERDICT_COLOR)
	column.add_child(_verdict_label)

	column.add_child(_make_label("Cabinet Fates", 18, HEADING_COLOR))
	_fates_box = VBoxContainer.new()
	_fates_box.name = "Fates"
	_fates_box.add_theme_constant_override("separation", 4)
	column.add_child(_fates_box)

	var play_again := Button.new()
	play_again.name = "PlayAgain"
	play_again.text = "Play Again"
	play_again.pressed.connect(_on_play_again_pressed)
	column.add_child(play_again)


# ------------------------------------------------------------------ the data

func _populate() -> void:
	var legacy := _generate()
	_verdict_label.text = str(legacy.get("verdict", ""))

	var fates: Array = []
	var raw_fates: Variant = legacy.get("cabinet_fates", [])
	if raw_fates is Array:
		fates = raw_fates
	for line in fates:
		_fates_box.add_child(_make_label("• " + str(line), 15, BODY_COLOR))


func _make_label(text: String, font_size: int, color: Color) -> Label:
	var label := Label.new()
	label.text = text
	label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	label.add_theme_font_size_override("font_size", font_size)
	label.add_theme_color_override("font_color", color)
	return label


# ------------------------------------------------------------- play again

func _on_play_again_pressed() -> void:
	if _state != null and _state.has_method("start_new_run"):
		_state.call("start_new_run")
		visible = false
	else:
		push_warning("EpilogueScreen: no GameState autoload found; cannot start a new run")
