/**
 * Writes docs/cast.md — every person in the game, and what decides who they
 * are.
 *
 *   npm run cast
 *
 * Generated rather than written, for the same reason the Godot content
 * tables are: a cast list transcribed by hand is a cast list that is wrong
 * within a month. Everything below is read out of the modules the game
 * actually runs on, so a temperament whose leak chance changes, a name added
 * to a pool, or a new strain shows up here on the next run without anybody
 * remembering to update a document.
 *
 * What is NOT generated is the prose between the tables. That is commentary,
 * and it is marked as such.
 */
import { writeFile } from "node:fs/promises";
import { OFFICES, FIRST, LAST } from "../src/game/cabinet.ts";
import { TEMPERAMENTS, TEMPERAMENT_KEYS } from "../src/game/temperament.ts";
import { CHIEF_NAME, CHIEF_TITLE } from "../src/game/chief.ts";
import {
  SPOUSE_FIRST, CHILD_FIRST, SPOUSE_LIVES, CHILD_LIVES, STRAINS,
} from "../src/game/family.ts";
import { FACTIONS } from "../src/game/congress.ts";
import { BLOCS } from "../src/game/blocs.ts";
import { CONVERSATIONS } from "../src/game/conversations.ts";
import { Engine } from "../src/game/engine.ts";

const out = [];
const w = (...lines) => out.push(...lines);

/** A markdown table from a header row and an array of cell arrays. */
function table(headers, rows) {
  w(`| ${headers.join(" | ")} |`);
  w(`| ${headers.map(() => "---").join(" | ")} |`);
  for (const row of rows) w(`| ${row.join(" | ")} |`);
  w("");
}

/** Escapes the one character that breaks a markdown table cell. */
const cell = (v) => String(v).replace(/\|/g, "\\|");

w("# The cast");
w("");
w("<!-- Generated by scripts/export-cast.mjs — run `npm run cast`. Do not edit. -->");
w("");
w("Almost nobody in this game is written. The Chief of Staff is, and the rest");
w("are drawn from the run's seed out of the pools below — which means a cast");
w("list is really a list of *what can be drawn*, plus the handful of people");
w("who are always the same.");
w("");

// ---------------------------------------------------------------- the fixed
w("## The one fixed person");
w("");
w(`**${CHIEF_NAME}** — ${CHIEF_TITLE}. Competence 91, loyalty 88, moderate,`);
w("temperament `institutionalist`. She is the only member of the cabinet whose");
w("numbers do not move with the seed, because she is the voice that teaches the");
w("job and a teacher who changes every run teaches nothing. Her lines live in");
w("`src/game/chief.ts` rather than being drawn from a temperament.");
w("");

// --------------------------------------------------------------- the offices
w("## The offices");
w("");
w("Six seats. The Chief of Staff is fixed; the other five are drawn fresh each");
w("run, and each one's domain is what their competence actually improves.");
w("");
table(["Office", "Title", "Domain"],
  OFFICES.map((o) => [`\`${o.key}\``, cell(o.title), `\`${o.domain}\``]));

// ----------------------------------------------------------- temperaments
w("## Temperaments");
w("");
w("Why a secretary is in the room — the third thing, after competence and");
w("loyalty. It decides what erodes them, what they bring to a crisis in their");
w("lane, and whether the day they stop believing in you ends with a resignation");
w("letter or a reporter's phone number.");
w("");
w(`There are ${TEMPERAMENT_KEYS.length} temperaments and five seats, dealt without replacement, so`);
w("every run seats five distinct ones and leaves a different one out. Who is");
w("missing is part of the cast.");
w("");
table(
  ["Temperament", "Who they are"],
  TEMPERAMENT_KEYS.map((k) => [`**${cell(TEMPERAMENTS[k].label)}** \`${k}\``, cell(TEMPERAMENTS[k].note)]),
);

w("### What wears them down");
w("");
w("Multipliers on the cabinet's base erosion, not absolute rates — each column");
w("averages about 1, so the overall turnover rate is unchanged and what varies");
w("is *which* of them goes and *why*. `Floor` is the loyalty ordinary");
w("unpopularity cannot take them below; scandal and unrest go straight through");
w("it. `Edge` is added to their competence on a crisis in their own department.");
w("");
table(
  ["Temperament", "Drift", "Approval", "Scandal", "Unrest", "Floor", "Leaks", "Edge"],
  TEMPERAMENT_KEYS.map((k) => {
    const t = TEMPERAMENTS[k];
    return [`\`${k}\``, t.baseDrift, t.approvalWeight, t.scandalWeight, t.unrestWeight,
      t.floor, `${Math.round(t.leakChance * 100)}%`, t.crisisEdge > 0 ? `+${t.crisisEdge}` : t.crisisEdge];
  }),
);

w("### What they say");
w("");
for (const k of TEMPERAMENT_KEYS) {
  const t = TEMPERAMENTS[k];
  w(`**${t.label}** \`${k}\``);
  w("");
  for (const line of t.linesLoyal) w(`- *loyal* — ${line}`);
  for (const line of t.linesSour) w(`- *sour* — ${line}`);
  w(`- *parting* — ${t.parting}`);
  w("");
}

// ------------------------------------------------------------------- names
w("## Where the names come from");
w("");
w(`Cabinet secretaries draw a first name from ${FIRST.length} and a surname from ${LAST.length}.`);
w("Both halves have to be unused, not just the full name: a cabinet holding a");
w("Yusuf Nakamura, a Yusuf Osei and a Naomi Osei reads as a bug.");
w("");
w(`**First** — ${FIRST.join(", ")}.`);
w("");
w(`**Surnames** — ${LAST.join(", ")}.`);
w("");
w(`**Spouse first names** (${SPOUSE_FIRST.length}) — ${SPOUSE_FIRST.join(", ")}.`);
w("");
w(`**Children's first names** (${CHILD_FIRST.length}) — ${CHILD_FIRST.join(", ")}.`);
w("");

// ------------------------------------------------------------------ family
w("## The family");
w("");
w("A spouse and two children, each with a life running whether you are in it or");
w("not. `personal.marriage` and `personal.family` are read off these people the");
w("way approval is read off the blocs: the scalar is a readout, not the model.");
w("");
table(
  ["Who", "Age", "Opening bond"],
  [
    ["Spouse", "your age −6 to +4", "68–80"],
    ["Elder child", "20–29", "62–78"],
    ["Younger child", "9 to (elder − 5)", "62–78"],
  ],
);

w("### What a spouse gave up");
w("");
for (const line of SPOUSE_LIVES) w(`- ${line}`);
w("");

w("### What a child is doing");
w("");
for (const band of CHILD_LIVES) {
  w(`**${band.min}–${band.max}**`);
  w("");
  for (const line of band.lines) w(`- ${line}`);
  w("");
}

w("### What they carry while you work");
w("");
table(
  ["Strain", "Who", "Ages", "Weight", "What it looks like"],
  STRAINS.map((s) => [
    `**${cell(s.label)}** \`${s.id}\``,
    s.kind,
    s.ages ? `${s.ages[0]}–${s.ages[1]}` : "any",
    s.weight,
    cell(s.detail),
  ]),
);

// ------------------------------------------------------------ the speakers
w("## Who can be talking");
w("");
w("A conversation beat names a *role*, not a person, and the role resolves");
w("against the actual state when the beat is shown — so a meeting written once");
w("still works after a reshuffle. `src/game/speaker.ts`.");
w("");
table(
  ["Role", "Resolves to", "Dress"],
  [
    ["`chief`, `treasury`, `state`, `defense`, `justice`, `health`", "whoever holds that office now", "suit"],
    ["`spouse`", "the spouse in `state.family`", "smart"],
    ["`child`", "the first child in `state.family`", "casual"],
    ["`press`", "the written figure — not simulated", "smart"],
    ["`ally`", "the written figure — not simulated", "suit"],
    ["`room`, `narrator`", "nobody; no face is drawn", "—"],
  ],
);

const speakers = new Map();
for (const conv of CONVERSATIONS) {
  for (const beat of Object.values(conv.beats ?? {})) {
    // A beat's speaker is `string | Speaker`; the bare string is the room
    // itself talking, and resolves to a `room` speaker with no face.
    const sp = typeof beat.speaker === "string"
      ? { role: "room", name: beat.speaker }
      : beat.speaker;
    if (!sp) continue;
    const key = `${sp.role}|${sp.name}`;
    if (!speakers.has(key)) speakers.set(key, { ...sp, where: new Set() });
    speakers.get(key).where.add(conv.label ?? conv.id);
  }
}
w("### Every speaker written into a meeting");
w("");
table(
  ["Name", "Role", "Title", "Mood", "Appears in"],
  [...speakers.values()].map((s) => [
    cell(s.name), `\`${s.role}\``, cell(s.title ?? ""), s.mood ? `\`${s.mood}\`` : "—",
    cell([...s.where].join("; ")),
  ]),
);

w("Seven moods are drawable: `neutral`, `warm`, `concerned`, `hostile`,");
w("`tired`, `amused`, `guarded`. A beat that sets none gets one inferred from");
w("its own text.");
w("");

// ---------------------------------------------------------- the not-people
w("## The groups");
w("");
w("Not characters, but they are who is in the room when a bill is counted, and");
w("a secretary's faction is drawn from the first list.");
w("");
w("### Congressional factions");
w("");
table(
  ["Faction", "Axis", "Party", "Backed by", "Hawks?", "What they are"],
  FACTIONS.map((f) => [
    `**${cell(f.name)}** \`${f.key}\``, f.axis, f.party ?? "swing", `\`${f.backing}\``,
    f.fiscal ? "yes" : "no", cell(f.blurb),
  ]),
);

w("### Voting blocs");
w("");
table(
  ["Bloc", "Share", "Volatility", "Blue / red lean", "What moves them"],
  BLOCS.map((b) => [
    `**${cell(b.name)}** \`${b.key}\``, `${Math.round(b.weight * 100)}%`, b.volatility,
    `${b.lean.blue >= 0 ? "+" : ""}${b.lean.blue} / ${b.lean.red >= 0 ? "+" : ""}${b.lean.red}`,
    cell(b.cares),
  ]),
);

// ------------------------------------------------------------- a real roll
w("## One actual run");
w("");
w("Seed 12345, so it is the same cast every time this file is regenerated.");
w("This is what the pools above produce, not a worked example.");
w("");
// Through the engine rather than createInitialState, because the cabinet and
// the family are drawn in newGame() and the order they are drawn in is what
// decides who you get.
const state = new Engine({ seed: 12345, party: "blue", name: "President Vance" }).state;
w("### The cabinet");
w("");
table(
  ["Name", "Office", "Competence", "Loyalty", "Faction", "Temperament"],
  state.cabinet.map((c) => [
    `**${cell(c.name)}**`, cell(c.title), c.competence, c.loyalty, `\`${c.faction}\``,
    `\`${c.temperament}\``,
  ]),
);
const missing = TEMPERAMENT_KEYS.filter(
  (k) => !state.cabinet.some((c) => c.office !== "chief" && c.temperament === k),
);
w(`Left out of this run: ${missing.map((k) => `\`${k}\``).join(", ")}.`);
w("");
w("### The family");
w("");
table(
  ["Name", "Who", "Age", "Bond", "Doing"],
  state.family.map((m) => [`**${cell(m.name)}**`, m.kind, m.age, m.bond, cell(m.doing)]),
);

await writeFile(new URL("../docs/cast.md", import.meta.url), out.join("\n"));
console.log(`docs/cast.md — ${out.length} lines`);
